### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by EchoYJJ** [AdaCompNUS/summit#10]
Hi! I'm new to SUMMIT.
In **https://adacompnus.github.io/summit-docs/references/releases/** , I find that the newest version is CARLA 0.9.8 and the Unreal Engine seems to be 4.22.
I'm curious about the process of updating. Until now, the uptodate version should be CARLA0.9.11 & UE4.24.

**Comment by LeeYiyuan** [comment]
Hi there! Unfortunately, due to some constraints on resources, we have not been able to update SUMMIT to match the newest version of CARLA, as we have hoped to. In the mean time, please use the latest SUMMIT version (built upon CARLA 0.9.8 + UE 4.22) for the best stability. 

Hope this helps!

**Comment by EchoYJJ** [comment]
@LeeYiyuan Thanks for your reply.
