### ISSUE TITLE
Issue with displaying maps 

### ISSUE THREAD

**Issue by tathagatoroy** [AdaCompNUS/summit#15]
Hi SUMMIT Team,
We are running SUMMIT with Unreal 4.22 in Ubuntu 18.04

We want to generate custom maps using OSM data.
So far We have followed the [documentation](https://adacompnus.github.io/summit-docs/) and tried to simulate the maps but the outputs displayed in the editor are just the red border outlines that are shown in the examples given in [here](https://adacompnus.github.io/summit-docs/references/summit_map_library/)

Following are the steps we are following.
After starting the simulation, we are running the extract_meshes.py followed by spawn_meshes.py script.
None of which is giving any error and the resulting output for Beijing and meske square is given below.

Beijing:
![Beijing](https://user-images.githubusercontent.com/42072694/174430669-d654c532-189b-4ce9-8f6f-d3c8a2d7f309.png)

Meskel Square:
![meskel square](https://user-images.githubusercontent.com/42072694/174430684-29934bb4-4b95-4fe5-a7d1-b49866de4149.png)

As you can see we are just getting the red outlined border and not the actual network
After this, we are running the download_inagery.py script. This is also not giving any error and is successfully downloading the images.

![Download_Imager](https://user-images.githubusercontent.com/42072694/174430891-40d6d871-a016-4bf7-8be3-154eb9ed18b8.jpg)

Following the above, we are running the spawn_imagery.py script. This is again giving no error and the resulting output in the UE4 Editor is unchanged from the previous screenshots.

We have tried running the same steps for custom locations using osm data and there also we are getting similar results.

We will be very grateful for any help that you can provide us in debugging the issue. Please let me know if I can provide any more information that would be useful to you guys for identifying the problem.

**Comment by LeeYiyuan** [comment]
Hi there,

SUMMIT relies on a bunch of custom assets, described [here](https://adacompnus.github.io/summit-docs/getting_started/building/) (in particular, EmptyMap and M_Tile) to load the meshes. 

Could you check if the EmptyMap you have loaded is the one we have provided, and if M_Tile exists in your assets?

**Comment by tathagatoroy** [comment]
Thanks for the prompt reply.

We have followed the steps described in the link you have attached. I rechecked and both the emptymap and M_Tile files exist in the prescribed folders and upon launching the server, the emptymap file present is being opened.

**Comment by LeeYiyuan** [comment]
Thank you for checking! I just took a closer look at the editor in your previous screenshot, and it indeed seems to contain the elements that our EmptyMap should have. 

However, I noticed that the world is missing a light source. It is possible that we might have left it out along the way. Can you try [placing a light source](https://docs.unrealengine.com/4.26/en-US/BuildingWorlds/LightingAndShadows/Basics/) to light up the world?

**Comment by tathagatoroy** [comment]
Thanks.That worked.
