### ISSUE TITLE
camera along with ego vehicle

### ISSUE THREAD

**Issue by tathagatoroy** [AdaCompNUS/summit#17]
Hi,
I wanted to run a agent vehicle like the one spawned using the script meskel_square_ego_vehicle.py, but along with it I want to place a camera on top of it which allows us to record and store the view of the vehicle.
What would be the best way to go about it ?

**Comment by cindycia** [comment]
You can refer to the code here: https://github.com/AdaCompNUS/context-pomdp/blob/5a4dad83126e923b6437d4396f5a820a23ed3649/summit_connector/src/spectator.py#L35-L53

Basically, it looks like:
`camera_sensor = world.spawn_actor(camera_blueprint, local_transform, attach_to=ego_vehicle_actor)`
