### ISSUE TITLE
failed to generate map in automatic_control.py or mannual_control.py

### ISSUE THREAD

**Issue by tpvt99** [AdaCompNUS/summit#18]
Hi Summit team,

The steps to get the errors are:
1. Download version 0.9.8e at https://adacompnus.github.io/summit-docs/references/releases/
2. Run Carla simulator, then run spawn_meshes.py, run spawn_imagery.py and run gamma_crowd.py
3. When I run automatic_control.py, the error is "RuntimeError: failed to generate map at line 89: `self.map = self.world.get_map()`.
4.  When I run mannual_control.py, the error is even clearer: 'RuntimeError: failed to generate map. The server could not send the OpenDRIVE (.xodr) file: Make sure it exists, has the same name of your town, and is correct'.

As indicated in point 4, I thought I did not have the map of meskel_square in .xodr format. Therefore, I use netconvert to convert the available meskel_square.osm in summit/Data to meskel_square.xodr and put in CarlaUE4/Content/Carla/Maps/OpenDrive. But it does not solve the issue.

Thank you for spending time to read my issue.

**Comment by LeeYiyuan** [comment]
Hi @tpvt99,

automatic_control.py and manual_control.py currently only work for built-in CARLA maps. For SUMMIT maps (OSM-based), they are untested. To replicate the scripts for SUMMIT maps, you will have to rewrite them using the SUMMIT-specific APIs.

Like you mentioned, netconvert has an OSM to XODR conversion, but we realized that there were some inaccuracies/loss of information during our development. Thus, the converted output may not work with scripts that utilize the XODR format.

**Comment by tpvt99** [comment]
Thank you Lee for a prompt response. I will write my own code to be able to use the script with summit maps.

**Comment by cindycia** [comment]
@tpvt99, to update you that we now removed these XODR-based scripts from our examples folder.

**Comment by tpvt99** [comment]
Thank you Panpan. That makes everything clear.
