### ISSUE TITLE
ModuleNotFoundError: No module named 'carla'

### ISSUE THREAD

**Issue by qiangyuchuan** [AdaCompNUS/summit#19]

**Comment by qiangyuchuan** [comment]
Hello there, I'm new to the summit simulator. After I download the version of summit_0.9.8e_lite and extract it in my worksapce, I can run the "./CarlaUE4.sh" and then a window popped up.

But when I  was running the "<summit_root>/PythonAPI/examples/spawn_meshes.py --dataset meskel_square" in the terminal, an error showed up as "ModuleNotFoundError: No module named 'carla'".

I have checked that my python do not have another version of the carla Python modules, I inspected my dictionary extracted from the first step, it appears some differences with this repo. For example, my ./carla folder is not contain the setup.py and source folder and my project root dict do not have the LibCarla folder. Do those missing contents have anything to do with the module not found issue?

Should I do anything about the issue above to fix it。

Looking forward to seeing your reply!

Thanks!

**Comment by coddiw0mple** [comment]
did you try  `pip install carla`

**Comment by LeeYiyuan** [comment]
Hi there,

Sorry for the very late reply. You may find #13 helpful.

**Comment by LeeYiyuan** [comment]
Hello there,

Sorry for the late reply. SUMMIT 0.9.8e_lite is only compatible with Python 2.7 and Python 3.6. If you are using some other python version, you will likely have to recompile SUMMIT in your environment.

**Comment by qiangyuchuan** [comment]
Thank you for the reply, I changed the python environment and it performed well.
