### ISSUE TITLE
Errors in following the tutorial of summit

### ISSUE THREAD

**Issue by YC-Liang** [AdaCompNUS/summit#22]
Hi,

I just downloaded summit following the instructions and followed the [tutorial](https://adacompnus.github.io/summit-docs/getting_started/running/) to try to run the examples.

The `spawn_meshes.py` and `gamma_crowd.py` examples run fine, but when running `spawn_imagery.py --dataset meskel_square` command, i get path not found error,
- e.g. `Path not found! 18/124481_159296`

More importantly, when running the `meskel_square_ego_vehicle.py` file, nothing happens for a long time until getting the following error,
`Traceback (most recent call last):
  File "meskel_square_ego_vehicle.py", line 295, in <module>
    main(args)
  File "meskel_square_ego_vehicle.py", line 253, in main
    target_position = ego_path.get_position(sumo_network, 5)
  File "meskel_square_ego_vehicle.py", line 86, in get_position
    return sumo_network.get_route_point_position(self.route_points[index])
IndexError: list index out of range
`

Here is an attachment of the carla interface i got from the two working commands,
![Screenshot from 2023-02-16 17-47-34](https://user-images.githubusercontent.com/27863214/219290818-e1b73fea-101d-4eba-8ad5-c145e48e7cf2.png)

As seen the navigating ego agent is not seen.
I am on Ubuntu 22.04.

Any guidance is appreciated. 
Thanks.

**Comment by LeeYiyuan** [comment]
@YC-Liang Thanks for raising the issues!

For `spawn_imagery.py`, please refer to this [link](https://adacompnus.github.io/summit-docs/tutorials/preparing_maps/) to download the proper image tiles -- essentially you will need to run:
```python3 download_imagery.py --dataset meskel_square```

For `meskel_square_ego_vehicle.py`: does it happen all the time, or only once every few tries?

**Comment by YC-Liang** [comment]
Thanks @LeeYiyuan. The images are downloaded and the `spawn_imagery.py` file runs fine now. 

The `meskel_square_ego_vehicle.py` doesn't seem to be working from the Carla interface. I assume when the file runs successfully, there will be a new vechile and intended trajectory shown on the map? In the terminal, the file will not report anything for a long time for about 2-3 mins and then terminate with above error. 

Also I run the `gamma_crowd.py` file in a terminal and the  `meskel_square_ego_vehicle.py` in another terminal, is this the intention?

**Comment by LeeYiyuan** [comment]
Sorry for the delay!

`meskel_square_ego_vehicle.py` does not do anything (in particular, it does not draw anything) apart from spawning a vehicle and controlling it to the end of a randomly chosen path. It is meant to be a template for how to script an ego-agent, and how to interact with the exo-agents.

The 2-3 minutes before terminating with an error corresponds to the time taken for the ego-agent to reach the end of the path. At the end of the path, the agent tries to access the "next waypoint index", which does not exist, leading to the error.

> Also I run the gamma_crowd.py file in a terminal and the meskel_square_ego_vehicle.py in another terminal, is this the intention?

Yes, `gamma_crowd.py` should be kept running separately to keep the crowd going.

**Comment by YC-Liang** [comment]
Awesome, thanks very much for the help.
