### ISSUE TITLE
Opendrive map use

### ISSUE THREAD

**Issue by gaohongfein** [AdaCompNUS/summit#6]
Hi Summit Team,
you have done a great job! I have a question. The osm or sumo map have a bit difference with opendrrive format map(.xodr). In carla, we create a scence with opendrive map(.xodr) ohne osm or sumo map. So How can we use opendrive map to run Summit? Where can I change ?

**Comment by LeeYiyuan** [comment]
Hi @gaohongfein, thank you for the interest in our work!

While we only support sumo maps, you can convert opendrive maps to sumo maps using this utility here (https://sumo.dlr.de/docs/Networks/Import/OpenDRIVE.html).
