### ISSUE TITLE
getting start error

### ISSUE THREAD

**Issue by weilianzhen** [AdaCompNUS/summit#7]
Hello!
I would like to try the summit.But, I can not login the following link:
https://adacompnus.github.io/summit-docs/setting_up
and 
https://adacompnus.github.io/references/releases

**Comment by weilianzhen** [comment]
Here is the error:

404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus

**Comment by cindycia** [comment]
Hey there,

You can try this two links:

https://adacompnus.github.io/summit-docs/getting_started/setting_up/

https://adacompnus.github.io/summit-docs/references/releases/

—Panpan

**Comment by LeeYiyuan** [comment]
Hi @15910693796,

Thanks for the heads up! It seems that there were a bunch of broken links on our docs, which we did not notice.

We have fixed them, and you should be able to arrive at the links mentioned by @cindycia.

Do let us know if any other errors come up :)

**Comment by weilianzhen** [comment]
> Hey there, You can try this two links: https://adacompnus.github.io/summit-docs/getting_started/setting_up/ https://adacompnus.github.io/summit-docs/references/releases/ —Panpan



> Hi @15910693796,
> 
> Thanks for the heads up! It seems that there were a bunch of broken links on our docs, which we did not notice.
> 
> We have fixed them, and you should be able to arrive at the links mentioned by @cindycia.
> 
> Do let us know if any other errors come up :)


It has been fixed. Thank you!
